### ISSUE TITLE
Support for --build-property

### ISSUE THREAD

**Issue by sidey79** [arduino/compile-sketches#16]
This action is a very interesting project.

Woud like to use this and also the report size delta action, but i think there is no option to pass multiple --build-property to the compile option.
I use this, to pass defines and specify the compiler path.

May support for this options can be added, my python isn't good enough to make a pr.

**Comment by per1234** [comment]
Hi @sidey79. Thanks for your interest in this action and for taking the time to make a feature request. I have now added the requested `--build-property` capability in this pull request: https://github.com/arduino/compile-sketches/pull/18

Rather than adding a dedicated action input for defining build properties, I decided to add a general purpose input that allows the user to insert any arbitrary flags into the `arduino-cli compile` command used to compile the sketch. This will allow for other advanced usages (e.g., `--export-binaries`). I provided a usage example in the PR message.

If you want to try it out and review the PR, that would be great. The updated action from my fork can be referenced like so:
```yaml
uses: per1234/compile-sketches@build-property
```
