### ISSUE TITLE
[Feature] Support Platform.local.txt

### ISSUE THREAD

**Issue by cuttingedge1109** [arduino/compile-sketches#23]
Hi there.
By using `platform.local.txt` file, we can override properties defined in platform.txt or define new properties without modifying platform.txt, as you know.
If the action supports `platform-file` section to import custom platform.local.txt file, it would be more flexible and powerful.
Regards.

**Comment by per1234** [comment]
Hi @cuttingedge1109. I have see multiple requests for this sort of control over the build properties, including most recently https://github.com/arduino/compile-sketches/issues/16

In order to accommodate these use cases, I added the `cli-compile-flags` input: https://github.com/arduino/compile-sketches/pull/18
This input allows you to define or override any build property via the `--build-property` flag of the `arduino-cli compile` command used by the action to compile the sketches:
https://arduino.github.io/arduino-cli/latest/commands/arduino-cli_compile/#options

So, from what I can see, the action already provides the capability you request, without the inconvenience of having to store platform.local.txt files in the repository or generate them on the fly.

If you find a real life use case that the current capabilities don't support, but the `platform.local.txt` approach would, please share it here and I'll investigate and give the request further consideration.
