### ISSUE TITLE
Add option to use path with spaces

### ISSUE THREAD

**Issue by umbynos** [arduino/compile-sketches#30]
@per1234 added an input that takes arbitrary flags that are passed to Arduino CLI during compilation, maybe can be useful.
The problem arises from https://github.com/arduino/arduino-cli/issues/1570

**Comment by per1234** [comment]
Thanks for your suggestion @umbynos. Since this is only relevant for testing Arduino boards platforms, which are not so plentiful as standalone libraries and sketches, I don't think it is worth adding an explicit path quoting check capability to `arduino/compile-sketches`. 

Instead, the boards platform maintainers who want this should configure it in their workflow, using the action's existing general purpose [`cli-compile-flags` input](https://github.com/arduino/compile-sketches#cli-compile-flags).

Here's an example of how that would be done: https://github.com/arduino/ArduinoCore-mbed/pull/435
